// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUTywXG3pgD_h7BSekg8zghFShIJPviCQ',
    appId: '1:688063218237:web:d7e3c7bd65d60404a3e054',
    messagingSenderId: '688063218237',
    projectId: 'tugasakhirmobile-f6cfa',
    authDomain: 'tugasakhirmobile-f6cfa.firebaseapp.com',
    storageBucket: 'tugasakhirmobile-f6cfa.appspot.com',
    measurementId: 'G-RGK5T7S2QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqzzjY5t2poot0OWNwN-p5Cc2_-cv9mbU',
    appId: '1:688063218237:android:e4b38c2e309bd777a3e054',
    messagingSenderId: '688063218237',
    projectId: 'tugasakhirmobile-f6cfa',
    storageBucket: 'tugasakhirmobile-f6cfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-kKJKmTM5YfMec-FBerQu4fu-P8RDzoQ',
    appId: '1:688063218237:ios:e8faf88fe566d47ea3e054',
    messagingSenderId: '688063218237',
    projectId: 'tugasakhirmobile-f6cfa',
    storageBucket: 'tugasakhirmobile-f6cfa.appspot.com',
    iosBundleId: 'com.example.appTugasAkhirMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-kKJKmTM5YfMec-FBerQu4fu-P8RDzoQ',
    appId: '1:688063218237:ios:e8faf88fe566d47ea3e054',
    messagingSenderId: '688063218237',
    projectId: 'tugasakhirmobile-f6cfa',
    storageBucket: 'tugasakhirmobile-f6cfa.appspot.com',
    iosBundleId: 'com.example.appTugasAkhirMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUTywXG3pgD_h7BSekg8zghFShIJPviCQ',
    appId: '1:688063218237:web:a4fd9ff78ed80101a3e054',
    messagingSenderId: '688063218237',
    projectId: 'tugasakhirmobile-f6cfa',
    authDomain: 'tugasakhirmobile-f6cfa.firebaseapp.com',
    storageBucket: 'tugasakhirmobile-f6cfa.appspot.com',
    measurementId: 'G-8XGQSKWWBB',
  );
}
